### ISSUE TITLE
If you seach for a specific ticket, it will not be displayed, especially if this a ticket with a lower number

### ISSUE THREAD

**Issue by azngeek** [fochlac/Tempo-Tracker#9] opened 2024-05-02 07:34 UTC
For example, when I have tickets with higher number ranges and I want to search for a ticket "TICKET-1", that that ticket would not show off in the results as only the newer ones will be displayed. 

For example, instead the result would be something like this:

1. TICKET-1235
2. TICKET-124
3. etc.

It would be helpful to search for a specific ticket.

**Comment by fochlac** [comment] 2024-05-02 07:45
Hi, quick testing showed me that the ticket is displayed, but at the very bottom. I noticed its not very visible, so did you try to scroll the list?

The results listed here are based on jira-smart-search, so I cannot easily add additional tickets. But I see two possible improvments here:

- [ ] add clearly visible scroll bar if the list overflows
- [ ] sort exact matches to the top of the list

If you check again and the issue is truly missing, I can have another look if I can check for exact matches. Also do you use jira datacenter or jira cloud?

**Comment by fochlac** [comment] 2024-05-02 08:58
Sounds like I'll have to do some additional manual matching here. Tbh. I don't use jira cloud or custom JQL-Queries, so they are not that well tested/maintained, since I don't have access to a jira-cloud instance with a tempo integration, ever since the free period ran out. 

Currently I'm using the https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-search/#api-rest-api-3-issue-picker-get endpoint with a base-query of `created >= "1900/01/01"`, but there are also some results based on the user history. 

I'll adapt this as follows:
- [ ] merge the user history based search results to the list
- [ ] if the search term looks like a issue key: use search to find results with jql `issueKey ="{searchTerm}"`

**Comment by azngeek** [comment] 2024-05-02 09:19
This sounds good. That regex will match for all tickets if this might help a little bit: 

`[a-zA-Z]{2,}\-\d+`

However, with this feature, the users might lose the “suggestions” as that would be an exact search. Maybe it would be more intuitive to match on "quotes" instead?

`"TICKET-1"` instead of `TICKET-1`

**Comment by fochlac** [comment] 2024-05-02 21:28
Should be fixed with 3.4.0, if you like the extension please leave a rating in the store, that will increase the visibility. :)

**Closed** 2024-05-03 16:42 UTC
